# Generated by Django 5.2 on 2026-03-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('desc', models.TextField(blank=True, null=True)),
                ('available_stocks', models.IntegerField(default=0)),
                ('price_per_unit', models.FloatField(default=0.0)),
                ('tax_percent', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_no', models.CharField(blank=True, max_length=15, null=True)),
                ('total_price_without_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rounded_net_price', models.IntegerField()),
                ('cash_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_bill',
            },
        ),
        migrations.CreateModel(
            name='SalesBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_at_sale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_at_sale', models.DecimalField(decimal_places=2, help_text='Tax Percent', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.product')),
                ('sales_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.salesbill')),
            ],
            options={
                'db_table': 'sales_bill_item',
            },
        ),
    ]
